# Makefile for EARTH Analysis Pipeline
# Run entire pipeline with: make all
# Clean outputs with: make clean

# ============================================================
# VARIABLES SECTION
# ============================================================

# Define the command to run R scripts
R := Rscript

# Define the command to render the Quarto report, placing output in output directory
QUARTO := quarto render code/EARTH_Analysis_Report.qmd --output-dir ../output

# ============================================================
# DIRECTORY PATHS
# ============================================================

# Directory containing all R code files (programs 0-4 and report)
CODE_DIR := code

# Directory containing data files (input and generated)
DATA_DIR := data

# Directory where figures/plots will be saved
FIG_DIR := figures

# Directory for miscellaneous outputs (RDS files, marker files)
MISC_DIR := misc

# Directory for other pipeline outputs
OUTPUT_DIR := output

# ============================================================
# OUTPUT FILE DEFINITIONS
# ============================================================

# Output from Step 0: imputed dataset after random forest imputation
IMPUTED_DATA := $(DATA_DIR)/imputed_EARTH.Rdata

# Outputs from Step 1: cleaned data with and without truncation
DATA_OUTPUTS := $(DATA_DIR)/afc_clean_trunc.Rdata $(DATA_DIR)/afc_clean_notrunc.Rdata

# Output from Step 2: figure files from chemical analysis and association tables
CHEM_OUTPUTS := $(FIG_DIR)/env_vars_notrunc.png $(FIG_DIR)/env_vars_trunc.png $(FIG_DIR)/AFC_histogram.png $(FIG_DIR)/outlier_grid.png $(FIG_DIR)/outlier_heatmap.png $(FIG_DIR)/date_diff_combined.png $(OUTPUT_DIR)/association_table_by_age.rds

# Outputs from Step 3: RDS files containing fitted IF score models (mu and pi)
IF_OUTPUTS := $(MISC_DIR)/fit_mu.RDS $(MISC_DIR)/fit_pi.RDS

# Output from Step 4: key output files from heterogeneity analysis
ANALYSIS_OUTPUTS := $(OUTPUT_DIR)/linear_projection_output.rds $(FIG_DIR)/edc_pairwise_correlations.png $(FIG_DIR)/teststat_scatter.png $(FIG_DIR)/cate_functions_full_linear.png $(FIG_DIR)/cate_functions_paper.png

# Final HTML report file generated by Quarto
REPORT := $(OUTPUT_DIR)/EARTH_Analysis_Report.html

# ============================================================
# MAIN TARGET
# ============================================================

# Mark 'all' as a phony target (not a real file, just a command name)
.PHONY: all

# Default target: when you run 'make' or 'make all', it runs the entire pipeline
# This depends on $(REPORT), which triggers all steps 0-4 through dependency chain
all: $(REPORT)
	# Print success message after everything completes (@ suppresses command echo)
	@echo "======================================"
	@echo "Pipeline completed successfully!"
	@echo "Report available at: $(REPORT)"
	@echo "Log file available at: $(OUTPUT_DIR)/makefile.log"
	@echo "======================================"

# ============================================================
# STEP 0: Data Generation and Imputation
# ============================================================

# Target: create imputed_EARTH.Rdata
# Dependency: this runs if the R script is newer than the output file
$(IMPUTED_DATA): $(CODE_DIR)/0_data_gen.R
	# Print status message to terminal
	@echo "======================================"
	@echo "Step 0: Data Generation and Imputation"
	@echo "This may take several minutes..."
	@echo "======================================"
	# Create the output directory if it doesn't exist (-p prevents errors if it exists)
	@mkdir -p $(OUTPUT_DIR)
	# Change to code directory and run program 0 using Rscript
	cd $(CODE_DIR) && $(R) 0_data_gen.R 2>&1 | tee -a ../$(OUTPUT_DIR)/makefile.log
	# Touch the output file to update its timestamp (tells Make this step is done)
	@touch $(IMPUTED_DATA)

# ============================================================
# STEP 1: Data Management
# ============================================================

# Target: create cleaned data files (with and without truncation)
# Dependencies: runs if program 1 OR imputed data is newer than output files
$(DATA_OUTPUTS): $(CODE_DIR)/1_data_man.R $(IMPUTED_DATA)
	# Print status message to terminal
	@echo "======================================"
	@echo "Step 1: Data Management"
	@echo "======================================"
	# Change to code directory and run program 1 using Rscript
	cd $(CODE_DIR) && $(R) 1_data_man.R 2>&1 | tee -a ../$(OUTPUT_DIR)/makefile.log
	# Touch both output files to update their timestamps
	@touch $(DATA_OUTPUTS)

# ============================================================
# STEP 2: Chemical Analysis
# ============================================================

# Target: create figure files from chemical analysis
# Dependencies: runs if program 2 OR cleaned data files are newer than figures
$(CHEM_OUTPUTS): $(CODE_DIR)/2_chem_analysis.R $(DATA_OUTPUTS)
	# Print status message to terminal
	@echo "======================================"
	@echo "Step 2: Chemical Analysis"
	@echo "======================================"
	# Create figures directory if it doesn't exist
	@mkdir -p $(FIG_DIR)
	# Change to code directory and run program 2 using Rscript
	cd $(CODE_DIR) && $(R) 2_chem_analysis.R 2>&1 | tee -a ../$(OUTPUT_DIR)/makefile.log
	# Touch output files to update their timestamps
	@touch $(CHEM_OUTPUTS)

# ============================================================
# STEP 3: IF Score Generation
# ============================================================

# Target: create RDS files containing fitted IF score models (fit_mu and fit_pi)
# Dependencies: runs if program 3 OR cleaned data files are newer than RDS files
$(IF_OUTPUTS): $(CODE_DIR)/3_IF_scores_gen.R $(DATA_OUTPUTS)
	# Print status message to terminal
	@echo "======================================"
	@echo "Step 3: IF Score Generation"
	@echo "This may take several minutes..."
	@echo "======================================"
	# Change to code directory and run program 3 using Rscript
	cd $(CODE_DIR) && $(R) 3_IF_scores_gen.R 2>&1 | tee -a ../$(OUTPUT_DIR)/makefile.log
	# Touch both RDS output files to update their timestamps
	@touch $(IF_OUTPUTS)

# ============================================================
# STEP 4: Heterogeneity Analysis
# ============================================================

# Target: create output files from heterogeneity analysis
# Dependencies: runs if program 4 OR IF score RDS files are newer than outputs
$(ANALYSIS_OUTPUTS): $(CODE_DIR)/4_IF_scores_analysis.R $(IF_OUTPUTS)
	# Print status message to terminal
	@echo "======================================"
	@echo "Step 4: Heterogeneity Analysis"
	@echo "======================================"
	# Create output directories if they don't exist
	@mkdir -p $(MISC_DIR)
	@mkdir -p $(OUTPUT_DIR)
	# Change to code directory and run program 4 using Rscript
	cd $(CODE_DIR) && $(R) 4_IF_scores_analysis.R 2>&1 | tee -a ../$(OUTPUT_DIR)/makefile.log
	# Touch output files to update their timestamps
	@touch $(ANALYSIS_OUTPUTS)

# ============================================================
# FINAL REPORT GENERATION
# ============================================================

# Target: create HTML report from Quarto markdown file
# Dependencies: runs if .qmd file OR analysis outputs are newer than HTML report
$(REPORT): $(CODE_DIR)/EARTH_Analysis_Report.qmd $(ANALYSIS_OUTPUTS)
	# Print status message to terminal
	@echo "======================================"
	@echo "Generating Final Report"
	@echo "======================================"
	# Render the Quarto document to HTML (command defined in QUARTO variable)
	$(QUARTO) 2>&1 | tee -a $(OUTPUT_DIR)/makefile.log
	# Remove intermediate Quarto output directory if it was created
	@rm -rf $(CODE_DIR)/output
	# Print completion message
	@echo "Report generated: $(REPORT)"

# ============================================================
# INDIVIDUAL STEP TARGETS
# ============================================================

# Mark these as phony targets (not real files, just command names)
.PHONY: step0 step1 step2 step3 step4 report

# Shortcut to run only Step 0 (data generation and imputation)
step0: $(IMPUTED_DATA)

# Shortcut to run only Step 1 (data management) - also runs Step 0 if needed
step1: $(DATA_OUTPUTS)

# Shortcut to run only Step 2 (chemical analysis) - also runs prior steps if needed
step2: $(CHEM_OUTPUTS)

# Shortcut to run only Step 3 (IF score generation) - also runs prior steps if needed
step3: $(IF_OUTPUTS)

# Shortcut to run only Step 4 (heterogeneity analysis) - also runs prior steps if needed
step4: $(ANALYSIS_OUTPUTS)

# Shortcut to generate only the report - assumes all steps 0-4 are complete
report: $(REPORT)

# ============================================================
# CLEANING TARGETS
# ============================================================

# Mark these as phony targets (not real files, just command names)
.PHONY: clean clean-all clean-report

# Remove only the HTML report and associated files
clean-report:
	# Print status message
	@echo "Removing report..."
	# Remove report from output directory
	rm -f $(REPORT)
	# Remove directory of report support files (plots, etc.)
	rm -rf $(OUTPUT_DIR)/EARTH_Analysis_Report_files

# Remove only intermediate files (keeps data but removes figures and outputs)
clean:
	# Print status message
	@echo "Removing intermediate outputs..."
	# No marker files to remove anymore - using actual output files

# Remove ALL generated outputs (WARNING: destructive!)
# This target depends on 'clean' and 'clean-report', so those run first
clean-all: clean clean-report
	# Print warning to user
	@echo "WARNING: This will remove ALL generated outputs!"
	@echo "Press Ctrl+C to cancel, or wait 3 seconds to proceed..."
	# Wait 3 seconds to give user time to cancel with Ctrl+C
	@sleep 3
	# Print status message
	@echo "Removing all generated files..."
	# Remove all files in figures directory
	rm -rf $(FIG_DIR)/*
	# Remove all files in output directory
	rm -rf $(OUTPUT_DIR)/*
	# Remove all RDS files in misc directory
	rm -f $(MISC_DIR)/*.RDS
	# Remove all Rdata files in data directory
	rm -f $(DATA_DIR)/*.Rdata
	# Remove all rds files in data directory (lowercase extension)
	rm -f $(DATA_DIR)/*.rds
	# Print completion message
	@echo "Clean complete. Data, figures, and outputs removed."

# ============================================================
# HELP TARGET
# ============================================================

# Mark help as a phony target
.PHONY: help

# Display help information about available make commands
help:
	# Print header
	@echo "EARTH Analysis Pipeline - Makefile Commands"
	@echo "==========================================="
	@echo ""
	# Print main commands section
	@echo "Main targets:"
	@echo "  make all          - Run entire local pipeline (steps 0-4) and generate report"
	@echo "  make report       - Generate HTML report (assumes steps 0-4 complete)"
	@echo ""
	# Print individual step commands section
	@echo "Individual steps:"
	@echo "  make step0        - Data generation and random forest imputation (slow)"
	@echo "  make step1        - Data management"
	@echo "  make step2        - Chemical analysis, association tables, and outlier detection"
	@echo "  make step3        - IF score generation (slow)"
	@echo "  make step4        - Heterogeneity analysis and plots"
	@echo ""
	# Print cleaning commands section
	@echo "Cleaning:"
	@echo "  make clean        - Remove intermediate marker files"
	@echo "  make clean-report - Remove report only"
	@echo "  make clean-all    - Remove ALL generated outputs (use with caution!)"
	@echo ""
	# Print other commands section
	@echo "Other:"
	@echo "  make help         - Show this help message"
	@echo ""
